// Bundle the observatory results into scripts/observatory/report.js, which the app loads with a
// <script> tag (no fetch needed) and shows on the 観測所 panel.
// Usage: node scripts/observatory/build_report.js --dir <folder with results> [--out report.js]
// Expects in --dir: obs_L7_base.json, obs_L7_waves.json, obs_L6_base.json, obs_L6_waves.json
// (from run.js --json), power_L7.txt, power_L6.txt (from power.js), popularity.json
// (popularity.py --json) and tickets.json (tickets.py --json).
'use strict';
const fs = require('fs');
const path = require('path');

const args = {};
for (let i = 2; i < process.argv.length; i++) if (process.argv[i].startsWith('--')) { args[process.argv[i].slice(2)] = process.argv[i + 1]; i++; }
const DIR = args.dir || '.';
const OUT = args.out || path.join(__dirname, 'report.js');
const read = f => { const p = path.join(DIR, f); return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null; };

function group(id) {
  if (id.startsWith('app_')) return 'app';
  if (id === 'combined' || id === 'combined_all' || id === 'bma') return 'combo';
  if (id.indexOf('Oracle') >= 0) return 'oracle';
  return 'obs';
}

function parsePower(text) {
  if (!text) return null;
  const out = { global: [], perSet: [] };
  for (const ln of text.split('\n')) {
    const m = ln.match(/^\s+(全セット共通の傾き|セット球ごとに別の傾き) ±(\d+)%: (.*)$/);
    if (!m) continue;
    const det = {};
    for (const part of m[3].split(' / ')) { const mm = part.match(/^(\S+) 検出(\d+)%/); if (mm) det[mm[1]] = +mm[2]; }
    (m[1] === '全セット共通の傾き' ? out.global : out.perSet).push({ s: +m[2], det });
  }
  return out;
}

function gameReport(key) {
  const base = read(`obs_${key}_base.json`), waves = read(`obs_${key}_waves.json`);
  if (!base) return null;
  const B = JSON.parse(base), W = waves ? JSON.parse(waves) : null;
  const lenses = [];
  const seen = new Set();
  const add = (row, nullKind, sims) => {
    if (seen.has(row.id)) return;
    seen.add(row.id);
    lenses.push({ id: row.id, label: row.label, group: group(row.id), p: +row.p.toFixed(4), avgHits: +row.avgHits.toFixed(3),
      gainPerDraw: +(1000 * row.gain / Math.max(1, row.n)).toFixed(2), nullKind, sims });
  };
  B.table.forEach(r => add(r, B.null, B.sims));
  if (W) W.table.filter(r => r.id.startsWith('app_') || r.id === 'combined_all').forEach(r => add(r, W.null, W.sims));
  const rank = B.setScore.rank;
  return {
    firstRound: B.firstRound, lastRound: B.lastRound, scored: B.scored,
    chanceHits: key === 'L7' ? 49 / 37 : 36 / 43,
    set: { top1: rank.top1 / rank.n, top3: rank.top3 / rank.n, n: rank.n, llPerDraw: rank.ll / rank.n, permP: B.setPerm.p },
    mixing: B.mixing || null,
    lenses,
    power: parsePower(read(`power_${key}.txt`)),
    popularity: popularityReport(key),
  };
}

// Popularity map (popularity.py / tickets.py --json): weights for the in-app ticket ranking plus
// the checks shown on the panel.
function popularityReport(key) {
  const pj = read('popularity.json'), tj = read('tickets.json');
  if (!pj || !tj) return null;
  const P = JSON.parse(pj)[key], T = JSON.parse(tj)[key];
  if (!P || !T) return null;
  return { rounds: P.rounds, n: P.n, walkForward: P.walkForward, w: P.w, lambda: T.jackpotLambda,
    quintiles: T.checkQuintiles.map(q => ({ jackpot: +q.jackpot.toFixed(3), n: q.n })) };
}

const jst = new Date(Date.now() + 9 * 3600e3).toISOString().slice(0, 16).replace('T', ' ') + ' JST';
const report = { generated: jst, games: { L7: gameReport('L7'), L6: gameReport('L6') } };
fs.writeFileSync(OUT, '// Generated by scripts/observatory/build_report.js - do not edit by hand.\n' +
  'window.GLEF_OBS_REPORT = ' + JSON.stringify(report, null, 1) + ';\n');
console.log('written', OUT, JSON.stringify(Object.fromEntries(Object.entries(report.games).map(([k, v]) => [k, v ? v.lenses.length + ' lenses' : 'missing']))));
