// Generated by scripts/observatory/build_report.js - do not edit by hand.
window.GLEF_OBS_REPORT = {
 "generated": "2026-10-02 11:03 JST",
 "games": {
  "L7": {
   "firstRound": 101,
   "lastRound": 696,
   "scored": 596,
   "chanceHits": 1.3243243243243243,
   "set": {
    "top1": 0.47818791946308725,
    "top3": 0.75,
    "n": 596,
    "llPerDraw": 0.5798520461613694,
    "permP": 0.000999000999000999
   },
   "mixing": [
    {
     "k": 1,
     "obs": 801,
     "mean": 790.001,
     "z": 0.463335876279192
    },
    {
     "k": 2,
     "obs": 794,
     "mean": 768.193,
     "z": 1.1020897102364886
    },
    {
     "k": 3,
     "obs": 759,
     "mean": 746.0805,
     "z": 0.5722018191749862
    }
   ],
   "lenses": [
    {
     "id": "uniform",
     "label": "何もしない（全部 同じ確率）",
     "group": "obs",
     "p": 0.7223,
     "avgHits": 1.237,
     "gainPerDraw": 0,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "eb_all",
     "label": "全期間の出現率だけ",
     "group": "obs",
     "p": 0.8252,
     "avgHits": 1.275,
     "gainPerDraw": -2.42,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "eb_recent",
     "label": "最近の出現率だけ",
     "group": "obs",
     "p": 0.8961,
     "avgHits": 1.287,
     "gainPerDraw": -3.36,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "eb_setmix",
     "label": "セット球の癖（次のセット球を予想して重みづけ）",
     "group": "obs",
     "p": 0.6963,
     "avgHits": 1.339,
     "gainPerDraw": -2.36,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "eb_transition",
     "label": "引っ張りの地図だけ",
     "group": "obs",
     "p": 0.7732,
     "avgHits": 1.232,
     "gainPerDraw": -0.43,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "eb_setOracle",
     "label": "【物理の検証用】当日のセット球を知っていた場合の癖",
     "group": "oracle",
     "p": 0.4945,
     "avgHits": 1.341,
     "gainPerDraw": -2.2,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_freqAll",
     "label": "単独: 全期間の出現率（ベイズ縮小）",
     "group": "obs",
     "p": 0.7013,
     "avgHits": 1.257,
     "gainPerDraw": -1.18,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_freqRecent",
     "label": "単独: 最近の出現率（半減期つき・ベイズ縮小）",
     "group": "obs",
     "p": 0.8611,
     "avgHits": 1.267,
     "gainPerDraw": -3.63,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_setTilt",
     "label": "単独: セット球ごとの癖（次のセット球の予想で重みづけ）",
     "group": "obs",
     "p": 0.7483,
     "avgHits": 1.285,
     "gainPerDraw": -2.69,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_setPull",
     "label": "単独: 同じセット球が前回使われた時の当選数字",
     "group": "obs",
     "p": 0.8691,
     "avgHits": 1.344,
     "gainPerDraw": -2.15,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_pull1",
     "label": "単独: 前回の本数字（引っ張り）",
     "group": "obs",
     "p": 0.4575,
     "avgHits": 1.289,
     "gainPerDraw": -1.33,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_pull2",
     "label": "単独: 2回前の本数字",
     "group": "obs",
     "p": 0.6623,
     "avgHits": 1.284,
     "gainPerDraw": -1.53,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_bonusPull",
     "label": "単独: 前回のボーナス数字",
     "group": "obs",
     "p": 0.999,
     "avgHits": 1.27,
     "gainPerDraw": -5.23,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_nbr1",
     "label": "単独: 前回の本数字の隣（±1）",
     "group": "obs",
     "p": 0.1818,
     "avgHits": 1.265,
     "gainPerDraw": -0.47,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_bonusNbr",
     "label": "単独: 前回のボーナス数字の隣（±1）",
     "group": "obs",
     "p": 0.0999,
     "avgHits": 1.31,
     "gainPerDraw": 0.32,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_gap",
     "label": "単独: 最後に出てからの回数（対数）",
     "group": "obs",
     "p": 0.7732,
     "avgHits": 1.344,
     "gainPerDraw": -1.78,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_hot10",
     "label": "単独: 直近10回の出現回数",
     "group": "obs",
     "p": 0.8911,
     "avgHits": 1.334,
     "gainPerDraw": -2.3,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_pos",
     "label": "単独: 数字の大きさ（小さい⇔大きい）",
     "group": "obs",
     "p": 0.8402,
     "avgHits": 1.31,
     "gainPerDraw": -2.07,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_pos2",
     "label": "単独: 数字の大きさ（両端⇔中央）",
     "group": "obs",
     "p": 0.2857,
     "avgHits": 1.339,
     "gainPerDraw": -0.87,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_digitPull",
     "label": "単独: 前回の本数字と同じ下一桁",
     "group": "obs",
     "p": 0.3876,
     "avgHits": 1.302,
     "gainPerDraw": -1.13,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_transition",
     "label": "単独: 引っ張りの地図（前回の各数字のあとに出やすい数字・ベイズ縮小）",
     "group": "obs",
     "p": 0.6074,
     "avgHits": 1.277,
     "gainPerDraw": -0.79,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "one_setPullOracle",
     "label": "【物理の検証用】単独: 当日と同じセット球の前回の当選数字",
     "group": "oracle",
     "p": 0.6474,
     "avgHits": 1.257,
     "gainPerDraw": -1.56,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "combined",
     "label": "全レンズの合成（重みは過去だけで学習）",
     "group": "combo",
     "p": 0.7542,
     "avgHits": 1.31,
     "gainPerDraw": -19.96,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "bma",
     "label": "レンズの成績で重みを毎回つけ直す合議（過去の成績だけ）",
     "group": "combo",
     "p": 0.98,
     "avgHits": 1.3,
     "gainPerDraw": -2.32,
     "nullKind": "fake",
     "sims": 1000
    },
    {
     "id": "app_depth",
     "label": "アプリの波 単独: depthWave（ギャップ）",
     "group": "app",
     "p": 0.7525,
     "avgHits": 1.287,
     "gainPerDraw": -1.67,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_vert",
     "label": "アプリの波 単独: vertWave（直近3回+WMA）",
     "group": "app",
     "p": 0.6148,
     "avgHits": 1.351,
     "gainPerDraw": -1.48,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_horz",
     "label": "アプリの波 単独: horzWave（ゾーンMACD）",
     "group": "app",
     "p": 0.9381,
     "avgHits": 1.253,
     "gainPerDraw": -2.54,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_cross",
     "label": "アプリの波 単独: crossWave（共起+相互情報量）",
     "group": "app",
     "p": 0.7325,
     "avgHits": 1.305,
     "gainPerDraw": -1.62,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_co",
     "label": "アプリの波 単独: coBias（キャリーオーバー）",
     "group": "app",
     "p": 0.9102,
     "avgHits": 1.341,
     "gainPerDraw": -1.59,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_fourier",
     "label": "アプリの波 単独: fourierWave（FFT周期）",
     "group": "app",
     "p": 0.1377,
     "avgHits": 1.317,
     "gainPerDraw": -0.15,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_markov",
     "label": "アプリの波 単独: markovWave（ゾーン遷移）",
     "group": "app",
     "p": 0.3653,
     "avgHits": 1.322,
     "gainPerDraw": -0.87,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_rqa",
     "label": "アプリの波 単独: rqaWave（再帰定量化）",
     "group": "app",
     "p": 0.6806,
     "avgHits": 1.295,
     "gainPerDraw": -1.76,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_cold",
     "label": "アプリの波 単独: coldWave（削除数字+KDE）",
     "group": "app",
     "p": 0.9681,
     "avgHits": 1.339,
     "gainPerDraw": -2.87,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_set",
     "label": "アプリの波 単独: setWave（セット球）",
     "group": "app",
     "p": 0.2375,
     "avgHits": 1.315,
     "gainPerDraw": -0.32,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_crossLoto",
     "label": "アプリの波 単独: crossLotoBias（他ロト引っ張り）",
     "group": "app",
     "p": 0.1038,
     "avgHits": 1.384,
     "gainPerDraw": 0.26,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_digit",
     "label": "アプリの波 単独: digitWave（下一桁）",
     "group": "app",
     "p": 0.6487,
     "avgHits": 1.299,
     "gainPerDraw": -1.79,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_wavelet",
     "label": "アプリの波 単独: waveletWave（Haar）",
     "group": "app",
     "p": 0.4052,
     "avgHits": 1.299,
     "gainPerDraw": -2.18,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_hmm",
     "label": "アプリの波 単独: hmmBias（HMM）",
     "group": "app",
     "p": 0.491,
     "avgHits": 1.337,
     "gainPerDraw": -1.75,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_lyapunov",
     "label": "アプリの波 単独: lyapunovBias（乗算調整器）",
     "group": "app",
     "p": 0.5389,
     "avgHits": 1.413,
     "gainPerDraw": -1.54,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_appTotal",
     "label": "アプリの波 単独: アプリの合計点（乗数すべて1.0）",
     "group": "app",
     "p": 0.2395,
     "avgHits": 1.29,
     "gainPerDraw": -0.7,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "app_waves",
     "label": "アプリの波を全部（重みは過去だけで学習）",
     "group": "app",
     "p": 0.7824,
     "avgHits": 1.329,
     "gainPerDraw": -19.25,
     "nullKind": "perm",
     "sims": 500
    },
    {
     "id": "combined_all",
     "label": "観測所のレンズ＋アプリの波（重みは過去だけで学習）",
     "group": "combo",
     "p": 0.7625,
     "avgHits": 1.362,
     "gainPerDraw": -42.28,
     "nullKind": "perm",
     "sims": 500
    }
   ],
   "power": {
    "global": [
     {
      "s": 3,
      "det": {
       "eb_all": 12,
       "eb_setmix": 15,
       "eb_setOracle": 12,
       "one_freqAll": 6,
       "bma": 9
      }
     },
     {
      "s": 5,
      "det": {
       "eb_all": 25,
       "eb_setmix": 26,
       "eb_setOracle": 26,
       "one_freqAll": 12,
       "bma": 19
      }
     },
     {
      "s": 8,
      "det": {
       "eb_all": 74,
       "eb_setmix": 79,
       "eb_setOracle": 76,
       "one_freqAll": 54,
       "bma": 75
      }
     },
     {
      "s": 12,
      "det": {
       "eb_all": 97,
       "eb_setmix": 98,
       "eb_setOracle": 97,
       "one_freqAll": 98,
       "bma": 99
      }
     }
    ],
    "perSet": [
     {
      "s": 5,
      "det": {
       "eb_all": 2,
       "eb_setmix": 7,
       "eb_setOracle": 8,
       "one_freqAll": 2,
       "bma": 4
      }
     },
     {
      "s": 10,
      "det": {
       "eb_all": 10,
       "eb_setmix": 21,
       "eb_setOracle": 27,
       "one_freqAll": 3,
       "bma": 10
      }
     },
     {
      "s": 15,
      "det": {
       "eb_all": 20,
       "eb_setmix": 47,
       "eb_setOracle": 83,
       "one_freqAll": 10,
       "bma": 36
      }
     },
     {
      "s": 25,
      "det": {
       "eb_all": 73,
       "eb_setmix": 97,
       "eb_setOracle": 100,
       "one_freqAll": 58,
       "bma": 94
      }
     }
    ]
   },
   "popularity": {
    "rounds": [
     11,
     668
    ],
    "n": 658,
    "walkForward": {
     "numbers only": 0.18968130322041116,
     "numbers + shape": 0.27891109133509995
    },
    "w": [
     0.036297559056642094,
     -0.0191055056453021,
     -0.013904743681518877,
     0.024514996442664555,
     0.01741240302524135,
     0.008245938254928304,
     0.0020703779788974926,
     0.01973839969365756,
     0.02331971347060178,
     0.015026584711500241,
     0.00810441015925232,
     0.013129630501530189,
     0.01089563502050852,
     -0.0011509536906984482,
     -0.0016766970543647332,
     0.0053429006512940086,
     -0.007532246640485188,
     -0.008526842707695438,
     -0.0015235215896487865,
     0.006468648619465984,
     -0.022587814706308405,
     -0.003968529820302264,
     0.0012131920244102478,
     0.003748890069663385,
     0.007516032685692401,
     -0.018010820351685077,
     -0.015205860715556043,
     0.010339375981204133,
     0.0086413174650132,
     -0.00003582741680661927,
     -0.006010931856066569,
     -0.0015872366073577313,
     -0.021318554321768008,
     0.0013240088205432009,
     -0.005339192465785771,
     -0.008657255421249916,
     -0.005856418805615412,
     -0.02505350207785378,
     -0.009371597177513371,
     -0.021124839615092858,
     0.0065837957312531925,
     0.003532990706495017,
     0.00525226167888791
    ],
    "lambda": 0.6916167664670658,
    "quintiles": [
     {
      "jackpot": 0.584,
      "n": 101
     },
     {
      "jackpot": 0.634,
      "n": 101
     },
     {
      "jackpot": 0.673,
      "n": 101
     },
     {
      "jackpot": 0.733,
      "n": 101
     },
     {
      "jackpot": 0.865,
      "n": 104
     }
    ]
   }
  },
  "L6": {
   "firstRound": 201,
   "lastRound": 2142,
   "scored": 1942,
   "chanceHits": 0.8372093023255814,
   "set": {
    "top1": 0.529351184346035,
    "top3": 0.7950566426364573,
    "n": 1942,
    "llPerDraw": 0.7366003497007783,
    "permP": 0.000999000999000999
   },
   "mixing": [
    {
     "k": 1,
     "obs": 1493,
     "mean": 1493.4795,
     "z": -0.013980413250527646
    },
    {
     "k": 2,
     "obs": 1446,
     "mean": 1459.3005,
     "z": -0.39503027675977986
    },
    {
     "k": 3,
     "obs": 1441,
     "mean": 1424.407,
     "z": 0.48494689143718434
    }
   ],
   "lenses": [
    {
     "id": "uniform",
     "label": "何もしない（全部 同じ確率）",
     "group": "obs",
     "p": 0.9203,
     "avgHits": 0.865,
     "gainPerDraw": 0,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "eb_all",
     "label": "全期間の出現率だけ",
     "group": "obs",
     "p": 0.289,
     "avgHits": 0.852,
     "gainPerDraw": -0.2,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "eb_recent",
     "label": "最近の出現率だけ",
     "group": "obs",
     "p": 0.7076,
     "avgHits": 0.84,
     "gainPerDraw": -1.11,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "eb_setmix",
     "label": "セット球の癖（次のセット球を予想して重みづけ）",
     "group": "obs",
     "p": 0.2558,
     "avgHits": 0.826,
     "gainPerDraw": -0.24,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "eb_transition",
     "label": "引っ張りの地図だけ",
     "group": "obs",
     "p": 0.3953,
     "avgHits": 0.85,
     "gainPerDraw": -0.03,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "eb_setOracle",
     "label": "【物理の検証用】当日のセット球を知っていた場合の癖",
     "group": "oracle",
     "p": 0.1761,
     "avgHits": 0.83,
     "gainPerDraw": -0.39,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_freqAll",
     "label": "単独: 全期間の出現率（ベイズ縮小）",
     "group": "obs",
     "p": 0.701,
     "avgHits": 0.85,
     "gainPerDraw": -0.39,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_freqRecent",
     "label": "単独: 最近の出現率（半減期つき・ベイズ縮小）",
     "group": "obs",
     "p": 0.804,
     "avgHits": 0.837,
     "gainPerDraw": -1,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_setTilt",
     "label": "単独: セット球ごとの癖（次のセット球の予想で重みづけ）",
     "group": "obs",
     "p": 0.5183,
     "avgHits": 0.838,
     "gainPerDraw": -0.35,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_setPull",
     "label": "単独: 同じセット球が前回使われた時の当選数字",
     "group": "obs",
     "p": 0.4352,
     "avgHits": 0.855,
     "gainPerDraw": -0.62,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_pull1",
     "label": "単独: 前回の本数字（引っ張り）",
     "group": "obs",
     "p": 0.8738,
     "avgHits": 0.831,
     "gainPerDraw": -0.88,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_pull2",
     "label": "単独: 2回前の本数字",
     "group": "obs",
     "p": 0.5249,
     "avgHits": 0.836,
     "gainPerDraw": -0.59,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_bonusPull",
     "label": "単独: 前回のボーナス数字",
     "group": "obs",
     "p": 0.412,
     "avgHits": 0.862,
     "gainPerDraw": -0.56,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_nbr1",
     "label": "単独: 前回の本数字の隣（±1）",
     "group": "obs",
     "p": 0.794,
     "avgHits": 0.846,
     "gainPerDraw": -0.78,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_bonusNbr",
     "label": "単独: 前回のボーナス数字の隣（±1）",
     "group": "obs",
     "p": 0.2392,
     "avgHits": 0.852,
     "gainPerDraw": -0.35,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_gap",
     "label": "単独: 最後に出てからの回数（対数）",
     "group": "obs",
     "p": 0.7807,
     "avgHits": 0.829,
     "gainPerDraw": -0.8,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_hot10",
     "label": "単独: 直近10回の出現回数",
     "group": "obs",
     "p": 0.7807,
     "avgHits": 0.851,
     "gainPerDraw": -0.78,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_pos",
     "label": "単独: 数字の大きさ（小さい⇔大きい）",
     "group": "obs",
     "p": 0.3256,
     "avgHits": 0.859,
     "gainPerDraw": -0.51,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_pos2",
     "label": "単独: 数字の大きさ（両端⇔中央）",
     "group": "obs",
     "p": 0.8904,
     "avgHits": 0.87,
     "gainPerDraw": -0.98,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_digitPull",
     "label": "単独: 前回の本数字と同じ下一桁",
     "group": "obs",
     "p": 0.9169,
     "avgHits": 0.811,
     "gainPerDraw": -0.99,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_transition",
     "label": "単独: 引っ張りの地図（前回の各数字のあとに出やすい数字・ベイズ縮小）",
     "group": "obs",
     "p": 0.6611,
     "avgHits": 0.852,
     "gainPerDraw": -0.42,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "one_setPullOracle",
     "label": "【物理の検証用】単独: 当日と同じセット球の前回の当選数字",
     "group": "oracle",
     "p": 0.1827,
     "avgHits": 0.846,
     "gainPerDraw": -0.31,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "combined",
     "label": "全レンズの合成（重みは過去だけで学習）",
     "group": "combo",
     "p": 0.8505,
     "avgHits": 0.817,
     "gainPerDraw": -9.89,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "bma",
     "label": "レンズの成績で重みを毎回つけ直す合議（過去の成績だけ）",
     "group": "combo",
     "p": 0.6844,
     "avgHits": 0.809,
     "gainPerDraw": -0.47,
     "nullKind": "fake",
     "sims": 300
    },
    {
     "id": "app_depth",
     "label": "アプリの波 単独: depthWave（ギャップ）",
     "group": "app",
     "p": 0.6844,
     "avgHits": 0.838,
     "gainPerDraw": -0.62,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_vert",
     "label": "アプリの波 単独: vertWave（直近3回+WMA）",
     "group": "app",
     "p": 0.4419,
     "avgHits": 0.824,
     "gainPerDraw": -0.54,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_horz",
     "label": "アプリの波 単独: horzWave（ゾーンMACD）",
     "group": "app",
     "p": 0.2691,
     "avgHits": 0.864,
     "gainPerDraw": -0.34,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_cross",
     "label": "アプリの波 単独: crossWave（共起+相互情報量）",
     "group": "app",
     "p": 0.3555,
     "avgHits": 0.85,
     "gainPerDraw": -0.43,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_co",
     "label": "アプリの波 単独: coBias（キャリーオーバー）",
     "group": "app",
     "p": 0.0166,
     "avgHits": 0.877,
     "gainPerDraw": 0.3,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_fourier",
     "label": "アプリの波 単独: fourierWave（FFT周期）",
     "group": "app",
     "p": 0.9701,
     "avgHits": 0.827,
     "gainPerDraw": -1.28,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_markov",
     "label": "アプリの波 単独: markovWave（ゾーン遷移）",
     "group": "app",
     "p": 0.1927,
     "avgHits": 0.851,
     "gainPerDraw": -0.16,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_rqa",
     "label": "アプリの波 単独: rqaWave（再帰定量化）",
     "group": "app",
     "p": 0.3787,
     "avgHits": 0.835,
     "gainPerDraw": -0.57,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_cold",
     "label": "アプリの波 単独: coldWave（削除数字+KDE）",
     "group": "app",
     "p": 0.3953,
     "avgHits": 0.843,
     "gainPerDraw": -0.47,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_set",
     "label": "アプリの波 単独: setWave（セット球）",
     "group": "app",
     "p": 0.4917,
     "avgHits": 0.84,
     "gainPerDraw": -0.19,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_crossLoto",
     "label": "アプリの波 単独: crossLotoBias（他ロト引っ張り）",
     "group": "app",
     "p": 0.0365,
     "avgHits": 0.84,
     "gainPerDraw": -0.82,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_digit",
     "label": "アプリの波 単独: digitWave（下一桁）",
     "group": "app",
     "p": 0.3389,
     "avgHits": 0.838,
     "gainPerDraw": -0.45,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_wavelet",
     "label": "アプリの波 単独: waveletWave（Haar）",
     "group": "app",
     "p": 0.9468,
     "avgHits": 0.824,
     "gainPerDraw": -1.33,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_hmm",
     "label": "アプリの波 単独: hmmBias（HMM）",
     "group": "app",
     "p": 0.0897,
     "avgHits": 0.827,
     "gainPerDraw": -0.09,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_lyapunov",
     "label": "アプリの波 単独: lyapunovBias（乗算調整器）",
     "group": "app",
     "p": 0.6877,
     "avgHits": 0.813,
     "gainPerDraw": -0.67,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_appTotal",
     "label": "アプリの波 単独: アプリの合計点（乗数すべて1.0）",
     "group": "app",
     "p": 0.6478,
     "avgHits": 0.834,
     "gainPerDraw": -0.63,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "app_waves",
     "label": "アプリの波を全部（重みは過去だけで学習）",
     "group": "app",
     "p": 0.0698,
     "avgHits": 0.848,
     "gainPerDraw": -6.87,
     "nullKind": "perm",
     "sims": 300
    },
    {
     "id": "combined_all",
     "label": "観測所のレンズ＋アプリの波（重みは過去だけで学習）",
     "group": "combo",
     "p": 0.0997,
     "avgHits": 0.804,
     "gainPerDraw": -16.61,
     "nullKind": "perm",
     "sims": 300
    }
   ],
   "power": {
    "global": [
     {
      "s": 3,
      "det": {
       "eb_all": 23,
       "eb_setmix": 23,
       "eb_setOracle": 17,
       "one_freqAll": 13,
       "bma": 22
      }
     },
     {
      "s": 5,
      "det": {
       "eb_all": 77,
       "eb_setmix": 77,
       "eb_setOracle": 72,
       "one_freqAll": 47,
       "bma": 67
      }
     },
     {
      "s": 8,
      "det": {
       "eb_all": 100,
       "eb_setmix": 100,
       "eb_setOracle": 100,
       "one_freqAll": 90,
       "bma": 100
      }
     },
     {
      "s": 12,
      "det": {
       "eb_all": 100,
       "eb_setmix": 100,
       "eb_setOracle": 100,
       "one_freqAll": 100,
       "bma": 100
      }
     }
    ],
    "perSet": [
     {
      "s": 5,
      "det": {
       "eb_all": 12,
       "eb_setmix": 15,
       "eb_setOracle": 20,
       "one_freqAll": 10,
       "bma": 15
      }
     },
     {
      "s": 10,
      "det": {
       "eb_all": 27,
       "eb_setmix": 65,
       "eb_setOracle": 97,
       "one_freqAll": 8,
       "bma": 38
      }
     },
     {
      "s": 15,
      "det": {
       "eb_all": 77,
       "eb_setmix": 98,
       "eb_setOracle": 100,
       "one_freqAll": 45,
       "bma": 100
      }
     },
     {
      "s": 25,
      "det": {
       "eb_all": 100,
       "eb_setmix": 100,
       "eb_setOracle": 100,
       "one_freqAll": 97,
       "bma": 100
      }
     }
    ]
   },
   "popularity": {
    "rounds": [
     11,
     2085
    ],
    "n": 2075,
    "walkForward": {
     "numbers only": 0.40339247492029295,
     "numbers + shape": 0.46502857575386486
    },
    "w": [
     0.07947908138287267,
     -0.016628469023868143,
     0.01925700622501254,
     0.03539480572063678,
     0.012279806941172755,
     0.030838245826991212,
     0.021996553445000223,
     0.019948161994811336,
     0.03723200482306791,
     0.01167900690423536,
     0.013951820990182821,
     0.03361672167923214,
     0.028860406926431114,
     0.006497847731525276,
     0.006417255801940976,
     0.013347942504932509,
     0.001575279699743671,
     0.018721830991260322,
     0.010946375732084053,
     -0.0031285175107498317,
     -0.019875591959369672,
     -0.0057595451934828335,
     0.002079653714448075,
     0.0181229321816446,
     0.01686961560395735,
     0.02010852829955432,
     -0.003498108254783515,
     0.01538813279686638,
     0.0030351497259524522,
     -0.007802491076096459,
     -0.020135318970448006,
     -0.01633331704556466,
     -0.015989897034342282,
     -0.016098422616745166,
     -0.029490197837126673,
     -0.021626734411517988,
     -0.013421802641643851,
     -0.004083619582769432,
     -0.011846211551871369,
     -0.008619409664251027,
     -0.05382557948228239,
     -0.032981236818644136,
     -0.04159662590502361,
     -0.055423989679912085,
     -0.005477435728140401,
     -0.0441776765433768,
     -0.005209420351800636,
     0.0236053026400434,
     0.010559837165973834
    ],
    "lambda": 1.9184652278177459,
    "quintiles": [
     {
      "jackpot": 1.161,
      "n": 355
     },
     {
      "jackpot": 1.285,
      "n": 355
     },
     {
      "jackpot": 1.493,
      "n": 355
     },
     {
      "jackpot": 1.859,
      "n": 355
     },
     {
      "jackpot": 2.254,
      "n": 355
     }
    ]
   }
  }
 }
};
